module.exports = {
    PEER_JOIN: "PEER_JOIN",
    PEER_LEAVE: "PEER_LEAVE",
    PEER_CHANNEL_READY: "PEER_CHANNEL_READY",
    MESSAGE: "MESSAGE",
    HANDSHAKE: "HANDSHAKE",
    CHANNEL_CLOSE: "CHANNEL_CLOSE",
    DATA: "DATA",
}